name: Publish Python distributions to PyPI

on:
  push:
    tags:
      - "*.*.*"
  workflow_run:
    workflows: ["Python CICD pipelines - Unittesting"]
    types:
      - completed

permissions:
  contents: read

jobs:
  build-publish:
    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') || github.event.workflow_run.conclusion == 'success' }}
    name: Build and publish Python distributions to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
          pip install wheel
          pip install setuptools
          pip install versionner
